# Generated by Django 2.2.6 on 2019-11-01 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tshirt', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirt',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='size',
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('gender', models.CharField(max_length=2)),
                ('size', models.CharField(max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='tshirt.Tshirt')),
            ],
        ),
    ]
