# Generated by Django 2.2.6 on 2019-11-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tshirt', '0003_auto_20191101_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='name',
            field=models.CharField(default='amfoss', max_length=255),
        ),
    ]
