# Generated by Django 2.2.6 on 2019-11-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tshirt', '0004_tshirt_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='slug',
            field=models.CharField(default='amfoss', max_length=255),
        ),
    ]
