# Generated by Django 2.2.6 on 2019-11-04 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tshirt', '0008_auto_20191103_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='tshirt.Tshirt'),
        ),
    ]
